id: D48FBB15C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:50:11+00:00'
last_modified: '2022-05-30T06:19:57.778571+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2078':
      image_group_id: I1PD95959
      title: ཤེས་རབ་བརྒྱ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1872
      order: 114
      base_file: 2078.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
