id: P411B2490
initial_creation_type: ocr
source_metadata:
  volumes:
    83a63aa6762447d9af80de8a09de812b:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ཤེས་རབ་བརྒྱ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1872
      volume_number: 114
