id: P411B2490
initial_creation_type: ocr
source_metadata:
  volumes:
    f93841b8dfb1440dad63a74279d55c68:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ཤེས་རབ་བརྒྱ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1872
      volume_number: 114
